// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SportShoeManagement.API.Data;

#nullable disable

namespace SportShoeManagement.API.Migrations
{
    [DbContext(typeof(SportShoeDbContext))]
    [Migration("20250718112415_InitialDB")]
    partial class InitialDB
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SportShoeManagement.API.Models.SportShoe", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("SportShoes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "Running",
                            IsDeleted = false,
                            Name = "Nike Air Zoom Pegasus",
                            Price = 120m
                        },
                        new
                        {
                            Id = 2,
                            Category = "Running",
                            IsDeleted = false,
                            Name = "Adidas Ultraboost",
                            Price = 150m
                        },
                        new
                        {
                            Id = 3,
                            Category = "Casual",
                            IsDeleted = false,
                            Name = "Puma Future Rider",
                            Price = 90m
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
